# Generated by Django 3.1.6 on 2021-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210220_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/productimage/', verbose_name='Фото товара'),
        ),
    ]
